### ISSUE TITLE
dicomtodicom mpr

### ISSUE THREAD

**Issue by vela1606** [dgobbi/vtk-dicom#101]
MPR pixel matrix acting weird

I've tried a few CT's and they all end up the same way.

<img width="1806" alt="screen shot 2016-08-17 at 2 08 57 pm" src="https://cloud.githubusercontent.com/assets/312212/17747753/3d0ea70a-6484-11e6-94fd-a01d35cc9af7.png">

**Comment by dgobbi** [comment]
Hi Vela,

If you have an image where the slice spacing is different from the pixel spacing, then the MPR generated by dicomtodicom will have anisotropic pixel spacing (i.e. the horizontal spacing will be different from the vertical spacing).  This is by design, since dicomtodicom currently has no options to interpolate the data.  But I might consider adding this feature in the future.

 - David

**Comment by dgobbi** [comment]
Commit 92331233 adds a --resample option to dicomtodicom that makes the pixel spacing the same in all directions.

**Comment by vela1606** [comment]
Works like a champ
Thanks!
