### ISSUE TITLE
Building with msvc 2013/2015 in Debug and RelWithDebInfo

### ISSUE THREAD

**Issue by edurante** [dgobbi/vtk-dicom#102]
Hi
Building vtk-dicom with msvc 2013/2015 is fine except that we end up with
1) librairies files in debug and relwithdebinfo having the same name. 
2) the install step did not copy the pdb files for both debug and relwithdebinfo

I did the following changes in a fork of vtk-dicom (maybe it can help)  
https://github.com/edurante/vtk-dicom/commit/1f7158d2ade9851ddd082235f2fbcfa2f6ff3cb7
With these changes 1) and 2) are fixed.

Thanks for this great package
Ernesto

**Comment by dgobbi** [comment]
Hi Ernesto, thanks for the feedback.

1) The "d" debug suffix is not standard for VTK libraries, so I'm not going to be using it for vtk-dicom.  If you need it, you can set it on the command line the first time you run cmake:

    cmake -D CMAKE_DEBUG_POSTFIX=d

2) When VTK starts installing pdb files, then I'll do it to.  I looked at your cmake code for this, and it looks incorrect... it should use $<CONFIGURATION> instead of having two separate rules.

I'm still a long ways away from making a binary package with libraries, much less one with debug libraries.  For now, the best way to use "debug" is to build your own projects with cmake, and to point them directly at the vtk-dicom build tree so that they can access the "Debug" directories there.
