### ISSUE TITLE
option to turn off header

### ISSUE THREAD

**Issue by toomanycats** [dgobbi/vtk-dicom#117]
Hello,
I like the program dicomtocsv, as it's a clean and fast way to build a database table.
I previously used dcmdump and parsed all fields I could stand.

The way I use dicomtocsv, is like so:
    $find <path> -type f | parallel -j -1 -n 1 -d "\n" 'dicomtocsv' > fifo
    # and concurrently
    $cat fifo >> inventory.csv

Perhaps I'm using the options incorrectly, but at the moment, I get a header printed on every line.

It would be nice to an option to not print a header at all. In addition , an option to only print a header.
That way I can use dicomtocsv in any way which I like.

Presently I made a branch where I test for 'level =4 ' and skip writing the header.

Cheers,
tmc

**Comment by dgobbi** [comment]
Hi tmc, I'm glad that you find dicomtocsv useful.  Yes, an option to remove the header line (or print just the header line) would be useful.  In fact I've even found myself having to sometimes add "| tail -n +2" in order to trim the header.

The dicomtocsv program has a lot of the capabilities of 'find' built into it, so pairing it with 'find' should be unnecessary.  I would recommend using it like this:

    dicomtocsv . -o inventory.csv

The command above will recursively search the current directory for all dicom files and, for each dicom series, it will add an entry to the csv file. Or if you want per-image information:

    dicomtocsv --image . -o inventory.csv

Using the "-o" versus redirecting stdout are equivalent except that "-o" allows stdio to be used to report progress.

Running it in parallel will probably not gain anything, since the scan is definitely IO-bound (if you have run benchmarks that show that running in parallel provides a speedup, I would be very interested in seeing them).

**Comment by toomanycats** [comment]
Thanks for responding. 

You're correct about the parallel, I highly doubt it is helping. It did help me when I used a script I wrote that was heavy in the use of sub shells (parsing dcmdump).

I also think the built in file writing (option -o) probably is fast too. 

I'm scanning 37x10^6 files right now, so speed helps, removing the pipes in my previous example call will help. I also hacked the source and removed the write header function when '--image' is invoked.

Thanks again for the tools.
cheers

**Comment by dgobbi** [comment]
The main thing is that, unlike dcmdump, dicomtocvs isn't meant to be run on each file independently.  It's best to give it a whole directory to chew on at once.

**Comment by toomanycats** [comment]
That makes sense.

I have a data dump of dicoms already in subject folders.

Is it still a good idea to use: `find root -type d | dicomtocsv -o output` ?

**Comment by toomanycats** [comment]
That makes sense.

I have a data dump of DICOMs in subject folders:

```for dir in *; do
        dicomtocsv  <dir flag> -o output 
done ```

**Comment by dgobbi** [comment]
I added a "--noheader" option in 3a2735a3.

If no input files are provided to dicomtocsv, it will just print the header:

    dicomtocsv --image  (or --series or --study)
