### ISSUE TITLE
Dicomtodicom change the value of "SliceThickness"

### ISSUE THREAD

**Issue by cogitas3d** [dgobbi/vtk-dicom#164]
Hey there!

I'm developing an addon that allow import DICOM on Blender 3D.

I use dicomtodicom to fix DICOM files that are incompatible with DicomToMesh and GDCM library and now I create a way to export slices like a nre DICOM file.

I use IMGTODCM to convert the PNG greyscale 8 bits to DCM and I suppose to use dicomtodicom to fix the incompatibility with DicomToMesh.

All works well, but I saw this difference:

Original file:
`(0018,0050) DS "SliceThickness" : [0.47] (4 bytes)`

After exported by dicomtodicom:
`(0018,0050) DS "SliceThickness" : [1] (2 bytes)`

![erro](https://user-images.githubusercontent.com/2422483/51009977-f5534780-1530-11e9-93d2-f8237c224a1b.png)

Look that in the Z axys the voxel data is deformed, because the value was changed from 0.47 to 1.

Do you know why this happen? And, have a way to fix this using a command file program?

Thanks for the attention and a big hug!

**Comment by dgobbi** [comment]
When dicomtodicom reads the images, it uses the ImagePositionPatient (0020,0032) attribute to determine the relative positions of the slices as required by the DICOM standard (PS 3.3 C.7.6.2) and ignores SliceThickness.  So my guess is that your ImagePositionPatient values are not valid, i.e. they are the same for every slice instead of incrementing for each slice.

If you can correctly set the ImagePositionPatient when you create the initial DICOM slices, the problem will go away.

Can you show me where I can download the IMGTODCM program you are using so that I can take a look at its output?

**Comment by cogitas3d** [comment]
Hi @dgobbi!

Thanks for the answer. I dont know very much about the field of radiology, to me this information is important to reconstruct the Dicom in 3D.

The Img2dcm link: https://bitbucket.org/tfmoraes/img2dcm

Thank you.

**Comment by cogitas3d** [comment]
I tryied to use dcmodify to force the value:

`for i in *; do dcmodify -m "(0020,0032)=0.67\0.67\0.47" $i; done`

It change the .dcm, but even this way, when I try to reconstruct the value of Z axis comeback to 1.

**Comment by dgobbi** [comment]
The position must advance for each slice, e.g.

    0.0\0.0\0.0
    0.0\0.0\0.47
    0.0\0.0\0.94
    ...

Thanks for the img2dcm link.

**Comment by cogitas3d** [comment]
Hi @dgobbi !

I try to solve it again a lot of times, and I read and study more the files. I saw that in the Original and IMG2DCM fies, the ImagePositionPatient is right! 

![captura de tela de 2019-01-12 20-41-52](https://user-images.githubusercontent.com/2422483/51079731-5010ae80-16ab-11e9-8d8b-755d65095646.png)

The dicomtodicom version is generated with that problem.

Looh the result od, for example, the 119 slice.

In Original:
```
(0020,0032) DS "ImagePositionPatient" : [108\-4\23] (10 bytes)
(0020,0037) DS "ImageOrientationPatient" : [-1\0\0\0\1\0] (12 bytes)
```

In IMG2DCM:
```
(0020,0032) DS "ImagePositionPatient" : [0.000000\0.000000\178.500000] (28 bytes)
```
Obs.: Was generated without "ImageOrientationPatient".


In dicomtodicom:
```
(0020,0032) DS "ImagePositionPatient" : [0\0\118] (8 bytes)
(0020,0037) DS "ImageOrientationPatient" : [1\0\0\0\1\0] (12 bytes)
```

I created a small DICOM voxel and send to Google Drive, if you want to see the result: https://drive.google.com/file/d/1ICgWO-cIquiHQEDRHO_VDvxPmgbdrHZ8/view?usp=sharing

Thank you!

**Comment by dgobbi** [comment]
Thanks for the files, they give me a much better idea of what is going on.

The IMG2DCM output is invalid, since ImagePositionPatient and ImageOrientationPatient are both required for CT and MR dicom files (since both these tags are required elements of the Image Plane Module).

When I inserted ImageOrientationPatient into the IMG2DCM files that you gave me, dicomtodicom produced slices with the correct spacing.  If ImageOrientationPatient is missing, dicomtodicom ignores the ImagePositionPatient information.  I don't consider that to be a bug, since both are required to define the image plane: if ImageOrientationPatient is missing, it's impossible to know left from right or front from back. 

When I applied dicomtodicom to the Original data, the output was correct.  Was this what you saw, as well?

(As an aside, note that you can't expect the SliceThickness to always be equal to the slice spacing.  In CT and MR acquisitions, it's common for the SliceThickness to be either greater than or less than the slice spacing).

**Comment by cogitas3d** [comment]
Perfect. I think I understand. Thank you very much!

**Comment by cogitas3d** [comment]
Hi @dgobbi !

I solve all the problems, thank you! I used Img2Dcm (Dcmtk version: https://support.dcmtk.org/docs/img2dcm.html) Python-Dicom to include values after generation.

Vídeo of DICOM importer/editor/exporter working (Portuguese): https://www.youtube.com/watch?v=o7esImmha5E

The homepage (Portuguese) of OrtogOnBlender: http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/OrtogOnBlender_Como_Funciona.html

A big hug!
