### ISSUE TITLE
niftitodicom output directory cannot end in \ if in double quotes

### ISSUE THREAD

**Issue by dmgroppe** [dgobbi/vtk-dicom#187]
niftitodicom.exe doesn't work if the output directory ends in a \ and the directory is enclosed in double quotes:

    niftitodicom.exe "C:\Users\My Name\demo.nii.gz" -o "C:\Users\My Name\DcmDir\"

If I remove the backslash, it works fine:

    niftitodicom.exe "C:\Users\My Name\demo.nii.gz" -o "C:\Users\My Name\DcmDir"

If the output directory is not enclosed in quotes, the output directory can end in a backslash.

**Comment by dgobbi** [comment]
Thanks for the report.  I have confirmed this and will work on a fix.

The problem seems to be that in the Windows shell, a backslash serves two purposes: in general, it is a path separator, but it becomes an escape character when placed in front of certain other characters (e.g. the double-quote character).

So if you type this into the shell, the quote is escaped and becomes part of the string (which means the string is, in fact, unterminated, but the shell passes it anyway):

    "DicomDir\"

The resulting string that is sent to the program is this:

    DicomDir"

Then, since the double-quote character is not allowed in a Windows filename, the program fails.  But I notice that Windows commands like `mkdir DicomDir\"` automatically strip the `"` from the end.  So I can make niftitodicom do the same.

**Comment by dmgroppe** [comment]
Thanks very much, David. :)

**Comment by dgobbi** [comment]
I found a stackoverflow answer that explains in gruesome detail how `\"` is interpreted by the shell in various situations: https://stackoverflow.com/a/31413730
