### ISSUE TITLE
How to insert custom private tag into vtkDICOMMRGenerator

### ISSUE THREAD

**Issue by qaler** [dgobbi/vtk-dicom#194]
Hi guys, is there any way to insert custom private tag (`0043|1101` for example) into meta data when writing dicom files?

Consider the following code snippet:

```c++
std::string file = "C:/IM0";
vtkSmartPointer<vtkDICOMReader> reader =
  vtkSmartPointer<vtkDICOMReader>::New();
reader->SetFileName(file.c_str());
reader->Update();
vtkNew<vtkDICOMMRGenerator> generator;
// Create a meta data object with some desired attributes.
vtkNew<vtkDICOMMetaData> meta;
meta->Set(DC::PatientName, "Medical-Emergency");

/// FIXME: this line does not work
meta->Set(static_cast<DC::EnumType>(0x00431101), "Custom Tag");

vtkNew<vtkDICOMWriter> writer;
writer->SetInputConnection(reader->GetOutputPort());
writer->SetMetaData(meta);
writer->SetGenerator(generator.GetPointer());
writer->SetFilePattern("%s/IM-%04.4d.dcm");
writer->SetFilePrefix("F:/");
writer->Write();
```

This program outputs:

> vtkDICOMMetaData (000001F78D38E4C0): SetAttributeValue: could not find tag ((0043,1101)) in the dictionary

Any help would be appreciated!

**Comment by dgobbi** [comment]
The dictionary error occurred because you did not specify a VR for the data element that you were adding.  It tried to look up the VR in the dictionary, and couldn't find it.

When setting private data elements, you must explicitly specify the VR.  But that's not all that you have to do.  Every private element must also have a private creator tag to go along with it (see [this part](http://dicom.nema.org/medical/DICOM/current/output/chtml/part05/sect_7.8.html) of the DICOM standard).

    typedef vtkDICOMVR VR;
    meta->Set(vtkDICOMTag(0x0043,0x0011), vtkDICOMValue(VR::LO, "Custom Creator"));
    meta->Set(vtkDICOMTag(0x0043,0x1101), vtkDICOMValue(VR::ST, "Custom Tag"));

Unfortunately, though, this will only get you so far, because the vtkDICOMMRGenerator will not yet write private tags into the output file.  The reason for this is that I haven't yet written a verifier for private data elements.

**Comment by qaler** [comment]
Which function should I override in class vtkDICOMMRGenerator (or vtkDICOMGenerator?) to implement writing private tags into output file?

**Comment by dgobbi** [comment]
Take a look at the GenerateMRInstance() method.  This method copies attributes from the SourceMetaData (i.e. the input meta data) and generates new MetaData that will be written to the file.  Right now, this method only copies attributes that are part of the Magnetic Resonance Image IOD, but you could override it so that it also copies private attributes.

**Comment by qaler** [comment]
Thank you dgobbi! I'll look into that method and post the source code once I get a proper result.

**Comment by qaler** [comment]
Overriding `vtkDICOMMRGenerator::GenerateMRInstance` does work! Many thanks @dgobbi !

```c++bool LabDICOMMRGenerator::GenerateMRInstance(vtkInformation *info)
{
    ...
    std::vector< DC::EnumType> tagsV;
    tagsV.push_back( DC::EnumType(0x00430011) );
    tagsV.push_back( DC::ItemDelimitationItem );
    typedef vtkDICOMVR VR;
    source->Set(vtkDICOMTag(0x0043,0x0011), vtkDICOMValue(VR::LO, "Custom Creator"));
    this->CopyOptionalAttributes(tagsV.data(), source);
    ...
    return true;
}
```
