### ISSUE TITLE
niftitodicom "--modality" flag has no effect

### ISSUE THREAD

**Issue by dmgroppe** [dgobbi/vtk-dicom#197]
I am unable to get the "--modality" flag to have any effect when using niftitodicom. For example, when I run the following command:
niftitodicom.exe -o C:\Users\me\SYNTH_DCM C:\Users\me\demo.nii.gz --modality SC

There is no "modality" field in the resultant dicom files. 

If I provide a dicom file as a source of metadata like so:
niftitodicom.exe -o C:\Users\me\SYNTH_DCM C:\Users\me\demo.nii.gz C:\Users\me\0.dcm --modality SC

Then the "modality" field of the resultant dicom files simply takes the value of that field in 0.dcm

Here is a link to demo.nii.gz if it helps to try to reproduce the issue:
https://www.dropbox.com/s/8ry3uvdn5h4qkon/demo.nii.gz?dl=0

**Comment by dgobbi** [comment]
The "--modality" flag is poorly named and incorrectly documented, and I apologize for that.

The true action of "--modality" is to select which of vtk-dicom's internal Generator classes are used (MRGenerator, CTGenerator, SCGenerator).  Essentially, it restricts the SOPClass or IOD.  It does not directly set the Modality attribute.  In a dump, you will see something like this:

    (0008,0016) UI "SOPClassUID" : [1.2.840.10008.5.1.4.1.1.7] {Secondary Capture Image Storage}

If you're wondering why it doesn't also set Modality to SC, it's because SC [is not a modality according to the DICOM standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html#sect_C.7.3.1.1.1).  For the Secondary Capture IODs, "Modality" is an optional attribute used to indicate the original scan modality, if known.

The manner of Secondary Capture is stored in the "Conversion Type" attribute (0008,0064) which can be set to these defined terms:

    DV    Digitized Video
    DI    Digital Interface
    DF    Digitized Film
    WSD   Workstation
    SD    Scanned Document
    SI    Scanned Image
    DRW   Drawing
    SYN   Synthetic Image

I chose to use "WSD" as the default.

**Comment by dmgroppe** [comment]
Ah-ha! Thanks very much for clarifying/educating @dgobbi
