### ISSUE TITLE
BUILD date not included

### ISSUE THREAD

**Issue by JensMunkHansen** [dgobbi/vtk-dicom#203]
Hi David

The DICOM_BUILD_DATE and DICOM_BUILD_TIME is not included for external builds or if the vtk_9 macros handles the inclusion of the Source directory. Is this on purpose?

Just a thing that I noted

**Comment by dgobbi** [comment]
Thanks for your note.  I hadn't noticed because at the time that I rearranged the CMakeLists.txt I was still doing my deployment builds with VTK 7.  The DICOM\_BUILD\_DATE is only used by some of the executables and nowhere else.  I'll consider what to do with it the next time I clean up the cmake files, it never worked properly on Windows, just Linux/UNIX.

**Comment by dgobbi** [comment]
I've removed the DICOM\_BUILD\_DATE and DICOM\_BUILD\_TIME variables as part of a simplification of the cmake scripts.
